/**
 * Metropolitan / Municipal / District assemblies (MMDAs) by region — aligned with
 * `GHANA_REGIONS` for pharmacy Part I district picker.
 */
import { GHANA_REGIONS, type GhanaRegion } from '@/theme/gh-regions';

export type MmdaPickerOption = { value: string; label: string };

export const GH_MMDA_BY_REGION: Record<GhanaRegion, readonly string[]> = {
  Ahafo: [
    'Asunafo North Municipal',
    'Asunafo South',
    'Asutifi North',
    'Asutifi South',
    'Tano North Municipal',
    'Tano South Municipal',
  ],

  Ashanti: [
    'Kumasi Metropolitan',
    'Asokwa',
    'Ejisu',
    'Juaben',
    'Kwabre East',
    'Obuasi',
    'Offinso',
    'Oforikrom',
    'Old Tafo',
    'Suame',
    'Mampong',
    'Asante Akim Central',
    'Asante Akim South',
    'Atwima Nwabiagya',
    'Bekwai',
    'Ejura-Sekyedumase',
    'Kwadaso',
    'Adansi Asokwa',
    'Adansi North',
    'Adansi South',
    'Afigya Kwabre North',
    'Afigya Kwabre South',
    'Ahafo Ano North',
    'Ahafo Ano South East',
    'Ahafo Ano South West',
    'Akrofuom',
    'Amansie Central',
    'Amansie West',
    'Amansie South',
    'Asante Akim North',
    'Atwima Kwanwoma',
    'Atwima Mponua',
    'Atwima Nwabiagya North',
    'Bosome Freho',
    'Bosomtwe',
    'Offinso North',
    'Sekyere Afram Plains',
    'Sekyere Central',
    'Sekyere East',
    'Sekyere Kumawu',
    'Sekyere South',
    // Commonly listed with the above; completes 43 MMDAs for Ashanti.
    'Obuasi East Municipal',
    'Asokore Mampong Municipal',
  ],

  Bono: [
    'Banda',
    'Berekum East Municipal',
    'Berekum West',
    'Dormaa Central Municipal',
    'Dormaa East',
    'Dormaa West',
    'Jaman North',
    'Jaman South Municipal',
    'Sunyani Municipal',
    'Sunyani West Municipal',
    'Tain',
    'Wenchi Municipal',
  ],

  'Bono East': [
    'Atebubu-Amanten Municipal',
    'Kintampo North Municipal',
    'Kintampo South',
    'Nkoranza North',
    'Nkoranza South Municipal',
    'Pru East',
    'Pru West',
    'Sene East',
    'Sene West',
    'Techiman Municipal',
    'Techiman North',
  ],

  Central: [
    'Cape Coast Metropolitan',
    'Agona West',
    'Assin Central',
    'Awutu Senya East',
    'Effutu',
    'Komenda-Edina-Eguafo-Abirem',
    'Mfantsiman',
    'Upper Denkyira East',
    'Abura Asebu Kwamankese',
    'Agona East',
    'Ajumako Enyan Esiam',
    'Asikuma Odoben Brakwa',
    'Assin North',
    'Assin South',
    'Awutu Senya West',
    'Ekumfi',
    'Gomoa East',
    'Gomoa Central',
    'Gomoa West',
    'Twifo Ati-Morkwa',
    'Twifo Hemang Lower Denkyira',
    'Upper Denkyira West',
  ],

  Eastern: [
    'Abuakwa North Municipal',
    'Abuakwa South Municipal',
    'Achiase',
    'Akuapem North Municipal',
    'Akuapem South',
    'Akyemansa',
    'Asene Manso Akroso',
    'Asuogyaman',
    'Atiwa East',
    'Atiwa West',
    'Ayensuano',
    'Birim Central Municipal',
    'Birim North',
    'Birim South',
    'Denkyembour',
    'Fanteakwa North',
    'Fanteakwa South',
    'Kwaebibirem Municipal',
    'Kwahu Afram Plains North',
    'Kwahu Afram Plains South',
    'Kwahu East',
    'Kwahu South',
    'Kwahu West Municipal',
    'Lower Manya Krobo Municipal',
    'New Juaben North Municipal',
    'New Juaben South Municipal',
    'Nsawam Adoagyiri Municipal',
    'Okere',
    'Suhum Municipal',
    'Upper Manya Krobo',
    'Upper West Akim',
    'West Akim Municipal',
    'Yilo Krobo Municipal',
  ],

  'Greater Accra': [
    'Accra Metropolitan',
    'Tema Metropolitan',
    'Ablekuma Central',
    'Ablekuma North',
    'Ablekuma West',
    'Adentan',
    'Ashaiman',
    'Ayawaso Central',
    'Ayawaso East',
    'Ayawaso North',
    'Ayawaso West',
    'Ga Central',
    'Ga East',
    'Ga North',
    'Ga South',
    'Ga West',
    'Korle Klottey',
    'Kpone Katamanso',
    'Krowor',
    'La Dade-Kotopon',
    'La-Nkwantanang Madina',
    'Ledzokuku',
    'Okaikwei North',
    'Tema West',
    'Weija-Gbawe',
    'Ada East',
    'Ada West',
    'Ningo-Prampram',
    'Shai-Osudoku',
  ],

  'North East': [
    'Bunkpurugu-Nakpanduri',
    'Chereponi',
    'East Mamprusi Municipal',
    'Mamprugu-Moagduri',
    'West Mamprusi Municipal',
    'Yunyoo-Nasuan',
  ],

  Northern: [
    'Tamale Metropolitan',
    'Sagnarigu Municipal',
    'Gushegu Municipal',
    'Karaga',
    'Kpandai',
    'Kumbungu',
    'Mion',
    'Nanton',
    'Nanumba North Municipal',
    'Nanumba South',
    'Saboba',
    'Tatale-Sangule',
    'Tolon',
    'Yendi Municipal',
    'Zabzugu',
    'Savelugu Municipal',
  ],

  Oti: [
    'Biakoye',
    'Jasikan',
    'Kadjebi',
    'Krachi East Municipal',
    'Krachi Nchumuru',
    'Krachi West',
    'Nkwanta North',
    'Nkwanta South Municipal',
    'Guan',
  ],

  Savannah: [
    'Bole',
    'Central Gonja',
    'East Gonja Municipal',
    'North Gonja',
    'North East Gonja',
    'Sawla-Tuna-Kalba',
    'West Gonja Municipal',
  ],

  'Upper East': [
    'Bawku Municipal',
    'Bawku West',
    'Binduri',
    'Bolgatanga Municipal',
    'Bolgatanga East',
    'Bongo',
    'Builsa North Municipal',
    'Builsa South',
    'Garu',
    'Kassena-Nankana Municipal',
    'Kassena-Nankana West',
    'Nabdam',
    'Pusiga',
    'Talensi',
    'Tempane',
  ],

  'Upper West': [
    'Daffiama Bussie Issa',
    'Jirapa Municipal',
    'Lambussie Karni',
    'Lawra Municipal',
    'Nadowli-Kaleo',
    'Nandom Municipal',
    'Sissala East Municipal',
    'Sissala West',
    'Wa Municipal',
    'Wa East',
    'Wa West',
  ],

  Volta: [
    'Adaklu',
    'Afadzato South',
    'Agotime-Ziope',
    'Akatsi North',
    'Akatsi South',
    'Anloga',
    'Central Tongu',
    'Ho Municipal',
    'Ho West',
    'Hohoe Municipal',
    'Keta Municipal',
    'Ketu North Municipal',
    'Ketu South Municipal',
    'Kpando Municipal',
    'North Dayi',
    'North Tongu',
    'South Dayi',
    'South Tongu',
  ],

  Western: [
    'Sekondi-Takoradi Metropolitan',
    'Ahanta West',
    'Effia-Kwesimintsim',
    'Jomoro',
    'Nzema East',
    'Prestea-Huni Valley',
    'Tarkwa-Nsuaem',
    'Wassa Amenfi East',
    'Wassa Amenfi West',
    'Ellembelle',
    'Mpohor',
    'Shama',
    'Wassa Amenfi Central',
    'Wassa East',
  ],

  'Western North': [
    'Aowin Municipal',
    'Bia East',
    'Bia West',
    'Bibiani-Anhwiaso-Bekwai Municipal',
    'Bodi',
    'Juaboso',
    'Sefwi Akontombra',
    'Sefwi-Wiawso Municipal',
    'Suaman',
  ],
};

/** Match free-typed or prefilled region text to a canonical region key. */
export function resolveGhanaRegionKey(
  input: string | null | undefined,
): GhanaRegion | null {
  if (!input?.trim()) return null;
  const t = input.trim();
  const exact = (GHANA_REGIONS as readonly string[]).find((r) => r === t);
  if (exact) return exact as GhanaRegion;
  const ci = (GHANA_REGIONS as readonly string[]).find(
    (r) => r.toLowerCase() === t.toLowerCase(),
  );
  return (ci as GhanaRegion) ?? null;
}

export function getMmdaPickerOptions(
  regionInput: string | null | undefined,
): readonly MmdaPickerOption[] {
  const key = resolveGhanaRegionKey(regionInput);
  if (!key) return [];
  const rows = GH_MMDA_BY_REGION[key];
  return rows.map((label) => ({ value: label, label }));
}
